language: perl

os:
  - linux

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24.0"
  - "5.24.1"
  - "5.24.2"
  - "5.22"

before_install:
  - cpanm -n Dist::Zilla::App::Command::cover
  - cpanm -n Devel::Cover::Report::Coveralls

install:
  - dzil authordeps --missing | cpanm -n || { cat ~/.cpanm/build.log ; false ; }
  - dzil listdeps   --missing | cpanm -n || { cat ~/.cpanm/build.log ; false ; }

script:
  - dzil test --author --release
  - dzil cover -report coveralls
